model_list:
  - model_name: ad-detect
    litellm_params:
      model: openai/lmstudio-loaded
      # model: openai/google/gemma-4-12b
      api_base: http://10.10.10.2:1234/v1
      api_key: os.environ/LM_STUDIO_API_KEY
      additional_drop_params: ["response_format"]

  - model_name: ad-detect-cloud
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY

litellm_settings:
  fallbacks: [{ "ad-detect": ["ad-detect-cloud"] }]
  request_timeout: 90
  drop_params: true

router_settings:
  disable_cooldowns: true
