#!/bin/sh

set -eu

sqlite3 /data/pihole/pihole-FTL.db ".backup /tmp/pihole-FTL.db"
gzip /tmp/pihole-FTL.db
podman run --rm -v /tmp:/tmp amazon/aws-cli -e AWS_USE_DUALSTACK=true s3 cp /tmp/pihole-FTL.db.gz s3://minube-backups/pihole-FTL.db.gz || {
	echo "Backup upload failed!"
	true
}
rm /tmp/pihole-FTL.db.gz
